name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: ondfisk-pango
  LOCATION: northeurope

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resources
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: ${{ env.LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./azuredeploy.bicep
          deploymentMode: Validate
          parameters: azuredeploy.parameters.json sqlServerPassword=${{ secrets.SQL_SERVER_PASSWORD }}
